image: registry.uninett.no/system/kubernetes-deploy:v0.4

variables:
  KUBE_PROD_DOMAIN: cal.uninett.no # The main domain for your application.
  KUBE_TEST_DOMAIN: cal.paas2.uninett.no # A domain which test versions of your application can be launched under.
  HTTP_PORT: '80' # The port number of the web server.

stages:
  - build
  - test
  - review
  - staging
  - production

build:
  stage: build
  script:
    - command build
  only:
    - branches

production:
  stage: production
  variables:
    CI_ENVIRONMENT_URL: https://$KUBE_PROD_DOMAIN
  script:
    - command deploy kubernetes/deployment.yaml
  environment:
    name: production
    url: http://$KUBE_PROD_DOMAIN
  when: manual
  only:
    - master

staging:
  stage: staging
  variables:
    CI_ENVIRONMENT_URL: http://staging.$KUBE_TEST_DOMAIN
  script:
    - command deploy kubernetes/deployment.yaml
  environment:
    name: staging
    url: http://staging.$KUBE_TEST_DOMAIN
  only:
    - master

review:
  stage: review
  variables:
    CI_ENVIRONMENT_URL: http://$CI_ENVIRONMENT_SLUG.$KUBE_TEST_DOMAIN
  script:
    - command deploy kubernetes/deployment.yaml
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_TEST_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
